### ISSUE TITLE
Using doctrine with Lumen

### ISSUE THREAD

**Issue by jnderr** [atrauzzi/laravel-doctrine#87]
Is anyone using this with Lumen? 

I copied doctrine.php into the config directory in the root of my project. 

in bootstrap/app.php

I added it as a service provider with:

$app->configure('doctrine');
$app->register('Atrauzzi\LaravelDoctrine\ServiceProvider');

But I get the error

I cannot seem to get it to work. 

I keep getting the error

Fatal error: Uncaught exception 'ReflectionException' with message 'Class path.storage does not exist' in vendor/laravel/framework/src/Illuminate/Container/Container.php on line 776

**Comment by Quagh** [comment]
Seems like this package pulls in the entire Laravel 5 framework. Of course that won't work with Lumen as most of it has been stripped down.

**Comment by atrauzzi** [comment]
Lumen is not Laravel, so I would not expect this package to work with it.

**Comment by Quagh** [comment]
@atrauzzi Are there any plans to support it though? Or guidelines on how to enable this ourselves, if at all possible?

**Comment by atrauzzi** [comment]
If you look at the exception you are getting, it's because services unique to Laravel aren't available.

This package targets those features and conventions.

You would ideally just make a lumen specific service provider and then ensure all the same stuff is happening as in my Laravel service provider... Except in a more lumen-y way.

**Comment by woss** [comment]
check this one out https://github.com/nordsoftware/lumen-doctrine
